function CONSTANS = COMPETITION_constants()

CONSTANS = struct;
CONSTANS.PATH.DATA = 'COMPETITION_DATA';
CONSTANS.PATH.DATA_DYNAMIC = fullfile(CONSTANS.PATH.DATA, 'COMPETITION_data_dynamic');
CONSTANS.PATH.DATA_STATIC = fullfile(CONSTANS.PATH.DATA, 'COMPETITION_data_static');
end

